[tool.uv]
package = false

[tool.pytest.ini_options]
norecursedirs = ["deps", ".git", ".venv", "build", "install", "log", "_meta"]
addopts = "-ra --strict-markers --import-mode=importlib"

[project]
name = "arena-rosnav"
version = "0.1.0"
description = ""
authors = [{ name = "Volodymyr Shcherbyna", email = "dev@voshch.dev" }]
maintainers = [{ name = "Volodymyr Shcherbyna", email = "dev@voshch.dev" }]
requires-python = "==3.12.*"
dependencies = [
    "pip",
    "colcon-common-extensions",
    "pytest",
    "lark",
    "rosdep",
    "PyYAML",
    "filelock",
    "scipy",
    "empy<4",
    "defusedxml",
    "lxml",
    "netifaces",
    "watchdog",
    "transforms3d",
    "opencv-python",
    "attrs",
    "shapely",
    "numpy",
    "setuptools<80",
    "pydantic",
    "pillow",
    "requests",
    "usd-core",
    "cattrs",
    "openai",
    "pycollada",
    "google-genai",
    "chromadb",
    "colourings",
    "aiofiles",
    "py-trees>=2.4.0",
    "pyastar2d>=1.1.4",
    "hypothesis",
    "pathfinding3d>=0.7.2",
    "transformers>=5.5.4",
    "huggingface_hub",
    "diffusers>=0.37.1",
    "rasterio>=1.5.0",
    "pyglet>=2.1.14",
    "msgpack>=1.0",
    "msgpack-numpy>=0.4.8",
    "pyzmq>=25",
    "pandas",
    "seaborn",
    "matplotlib",
    "polars",
    "rosbags",
    "pyarrow",
    "plotly",
    "mcap",
    "mcap-ros2-support",
    "sounddevice>=0.5.5",
    "pyroomacoustics>=0.10.1",
]

[build-system]
requires = ["setuptools<80", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "aiomonitor>=0.7.1",
]

[tool.ruff]
target-version = "py312"
line-length = 320
src = [
    "arena_runtime/arena_runtime/arena_runtime",
    "task_generator/task_generator",
    "arena_bringup/arena_bringup",
    "arena_robots/arena_robots/arena_robots",
    "arena_simulation_setup/src/arena_simulation_setup",
    "utils/arena_rclpy_mixins/arena_rclpy_mixins",
    "utils/rviz_utils/rviz_utils",
    "utils/human_steering/human_steering",
    "utils/arena_cam/arena_cam",
]
extend-exclude = [
    "_meta",
    "arena_tools",
    "arena_isaac",
    "arena_evaluation",
    "arena_training",
    "arena_robots/deps",
    "arena_planners/planners",
    ".venv",
    "**/launch",
    "**/*.launch.py",
    "**/scripts",
    "**/setup.py",
    "**/tests",
    "**/test",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "UP", "B", "ANN", "PYI"]
ignore = ["E501", "E402", "F841", "E731", "PYI051", "E741", "UP035"]

[tool.ruff.lint.per-file-ignores]
"arena_simulation_setup/**/*.py" = ["UP"]
"utils/arena_rclpy_mixins/**/*.py" = ["UP046", "UP047"]

[tool.ruff.lint.flake8-annotations]
suppress-none-returning = true
mypy-init-return = true
allow-star-arg-any = true

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
