services:
  arena:
    image: "${ARENA_IMAGE}"
    pull_policy: "never"
    build:
      context: .
      dockerfile: src/Arena/_meta/docker/features/docker/Dockerfile
      args:
        - gid=${HOST_GID}
        - uid=${HOST_UID}
    devices:
      - "/dev/snd:/dev/snd"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/run/user/${HOST_UID}/pulse:/tmp/pulse"
      - "shared:/tmp/shared"
      - "$HOST_ARENA_WS_DIR/src/Arena/.venv:/opt/venv"
      - "$HOST_ARENA_WS_DIR/src:/opt/arena_ws/src"
      - "$HOST_ARENA_WS_DIR/build:/opt/arena_ws/build"
      - "$HOST_ARENA_WS_DIR/install:/opt/arena_ws/install"
      - "$HOST_ARENA_WS_DIR/log:/opt/arena_ws/log"
      - "$HOST_ARENA_WS_DIR/.uv-python:/opt/arena_ws/.uv-python"
      - "$HOST_ARENA_WS_DIR/.uv-cache:/opt/arena_ws/.uv-cache"
      - "$HOST_ARENA_WS_DIR/.env:/opt/arena_ws/.env"
      - "$HOST_ARENA_DATA_DIR:/opt/arena_ws/data"
    environment:
      - QT_X11_NO_MITSHM=1
      - TMPDIR=/tmp/shared
      - DISPLAY
      - PULSE_SERVER=unix:/tmp/pulse/native
      - UV_LINK_MODE=copy
      - UV_PYTHON_INSTALL_DIR=/opt/arena_ws/.uv-python
      - UV_CACHE_DIR=/opt/arena_ws/.uv-cache
      - AMENT_CMAKE_VENV_UV_OVERRIDES=/opt/arena_ws/src/Arena/_meta/docker/uv-overrides.txt
      - ARENA_IMAGE
      - ARENA_IMAGE_TAG
      - ARENA_PROJECT_NAME
      - ARENA_ROS_DISTRO
      - HOST_UID
      - HOST_GID
      - HOST_ARENA_WS_DIR
      - HOST_ARENA_DATA_DIR
      - ARENA_DATA_DIR=/opt/arena_ws/data
      - ROSNAV_AGENTS_DIR=/opt/arena_ws/data/agents
      - HF_HOME=/opt/arena_ws/data/hf
      - LLM_API_ENDPOINT
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - CYCLONEDDS_URI=file:///opt/arena_ws/src/Arena/_meta/docker/cyclonedds.xml
      - FASTRTPS_DEFAULT_PROFILES_FILE=/opt/arena_ws/src/Arena/_meta/docker/fastdds.xml
    env_file:
      - .env
    user: "${HOST_UID}"
    group_add:
      - sudo
      - audio
    network_mode: host
    command: ["bash"]
    stdin_open: true 
    tty: true
    healthcheck:
      test: ["CMD", "test", "-f", "/.built"]
      interval: 1s
      timeout: 2s
      retries: 99999 # if you can't build by then, good juck
      start_period: 0s
    ports:
      - 50101
      - 50102

volumes:
  shared:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
