assets:
  footstep:
    category: footstep
    semantic_tags: [human, movement, transient]
    reference_level_db: 45.0
    reference_distance_m: 1.0
    normalization_dbfs: -6.0
    loop: false

    variants:
      - sample_id: footstep_default_01
        file: footstep_default.wav
        tags: [walk, default]
        octave_band_levels_db: auto

      - sample_id: footstep_walnut_planks_01
        file: footstep_walnut_planks.wav
        tags: [walk, walnut_planks]
        octave_band_levels_db: auto

      - sample_id: footstep_oak_planks_01
        file: footstep_oak_planks.wav
        tags: [walk, oak_planks]
        octave_band_levels_db: auto

      - sample_id: footstep_marble_tile_01
        file: footstep_marble_tile.wav
        tags: [walk, marble_tile]
        octave_band_levels_db: auto

      - sample_id: footstep_smooth_concrete_01
        file: footstep_smooth_concrete.wav
        tags: [walk, smooth_concrete]
        octave_band_levels_db: auto

      - sample_id: footstep_ceramic_tile_01
        file: footstep_ceramic_tile.wav
        tags: [walk, ceramic_tile]
        octave_band_levels_db: auto

  greeting:
    category: speech
    semantic_tags: [human, vocalization, greeting]
    reference_level_db: 60.0
    reference_distance_m: 1.0
    normalization_dbfs: -6.0
    loop: false

    variants:
      - sample_id: greeting_01
        file: greeting.wav
        tags: [neutral, adult]
        octave_band_levels_db: auto

  motor:
    category: mechanical
    semantic_tags: [robot, movement]
    reference_level_db: 55.0
    reference_distance_m: 1.0
    normalization_dbfs: -9.0
    playback_gain_db: 0.0
    loop: false

    variants:
      - sample_id: motor_sound_01
        file: short_motor_sound.wav
        tags: [robot, motor]
        octave_band_levels_db: auto

  motor_start:
    playback_gain_db: -3.0
    category: mechanical
    semantic_tags: [robot, movement, motor, start]
    reference_level_db: 55.0
    reference_distance_m: 1.0
    # normalization_dbfs: -9.0
    loop: false
    variants:
      - sample_id: motor_start_01
        file: long_motor_sound_start.wav
        tags: [robot, motor, start]
        octave_band_levels_db: auto

  motor_loop:
    playback_gain_db: -3.0
    category: mechanical
    semantic_tags: [robot, movement, motor, steady]
    reference_level_db: 55.0
    reference_distance_m: 1.0
    # normalization_dbfs: -9.0
    loop: true
    variants:
      - sample_id: motor_loop_01
        file: long_motor_sound_middle.wav
        tags: [robot, motor, steady]
        octave_band_levels_db: auto

  motor_stop:
    playback_gain_db: -3.0
    category: mechanical
    semantic_tags: [robot, movement, motor, stop]
    reference_level_db: 55.0
    reference_distance_m: 1.0
    # normalization_dbfs: -9.0
    loop: false
    variants:
      - sample_id: motor_stop_01
        file: long_motor_sound_end.wav
        tags: [robot, motor, stop]
        octave_band_levels_db: auto
