controller_plugins:
  - FollowPath

controller_plugins_dict:
  FollowPath:
    plugin: "nav2_pas_crowdnav_controller/PasCrowdNavController"
    lookahead_dist: 0.8
    v_max: 2.0               # Normal cruise speed
    v_min: 0.2               # Creep speed when arriving at goal
    slowdown_dist: 1.0       # Start slowing down 1 meter before the goal
    rotation_threshold: 0.35
    transform_tolerance: 0.2
  
  goal_checker:
    plugin: "nav2_controller::SimpleGoalChecker"
    xy_goal_tolerance: 0.35
    yaw_goal_tolerance: 1.35
    stateful: True
    
  progress_checker:
    plugin: "nav2_controller::SimpleProgressChecker"
    required_movement_radius: 0.1
    movement_time_allowance: 10.0
