<?xml version="1.0"?>
<package format="2">
  <name>arena_bringup</name>
  <version>0.0.0</version>
  <description>The arena_bringup package</description>

  <maintainer email="dev@voshch.dev">voshch</maintainer>

  <license>MIT</license>
  
  <depend>rclpy</depend>
  <depend>arena_rclpy_mixins</depend>
  <depend>nav2_msgs</depend>
  <depend>joint_state_publisher</depend>
  <depend>nav2_map_server</depend>
  <depend>navigation2</depend>
  <depend>nav2_bringup</depend>
  <depend>nav2_waypoint_follower</depend>

  <depend>bondcpp</depend>
  <depend>behaviortree_cpp_v3</depend>
  <depend>diagnostics</depend>
  <depend>angles</depend>
  <depend>slam_toolbox</depend>

  <exec_depend>gz_ros2_control</exec_depend>
  <exec_depend>ros2controlcli</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>diff_drive_controller</exec_depend>
  <exec_depend>mecanum_drive_controller</exec_depend>
  <exec_depend>twist_stamper</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
