/**:
  ros__parameters:
    task:
      parametrized:
        file: default.xml
      random:
        dynamic:
          n: [0, 0]
          models:
          - arenian
        interactive:
          n: [0, 0]
          models:
          - shelf
        static:
          n: [0, 0]
          models:
          - shelf
      scenario:
        file: default
      staged:
        curriculum: default.yaml
        index: 0
      environment:
        file: office.yaml